# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "张偶的网络日志"
description:        ""

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "关于我"
    href:           "/about.html"
  - name:           "GitHub"
    href:           "//github.com/comehope"
  - name:           "知乎"
    href:           "//www.zhihu.com/people/zhang-ou-15"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

port: 4001

gems: []